package weather.app;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import static weather.app.ThemeColor.backgroundColor;
import static weather.app.ThemeColor.mountains;
import static weather.app.WeatherApp.screenHeight;
import static weather.app.WeatherApp.screenWidth;
import static weather.app.WeatherForecast.getCurrentWeatherDetails;

/**
 *
 * @author Kamil
 */
public class WeatherUI extends javax.swing.JFrame {

    public static int cordsX;
    public static int cordsY;
    public static int mouseX;
    public static int mouseY;
    /**
     * Creates new form WeatherUI
     */
    public WeatherUI() {
        initComponents();
        int positionY = (screenHeight - 518)/2;
        int positionX = (screenWidth - 300)/2;
        this.setLocation( positionX , positionY );
        this.setSize(320, 518);
        this.setTitle("WeatherApp");
        this.setDefaultCloseOperation(3);
        this.setBackground(new Color(1.0f,1.0f,1.0f,0f));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/weather_icons/app_icon.png")));
        menu.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        dayAfterTomorrowTempLabel = new javax.swing.JLabel();
        nextDayTempLabel = new javax.swing.JLabel();
        placeholderLabel = new javax.swing.JLabel();
        nextDayImage1 = new javax.swing.JLabel();
        nextDayCondLabel1 = new javax.swing.JLabel();
        nextDayLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nextDayCondLabel = new javax.swing.JLabel();
        nextDayLabel = new javax.swing.JLabel();
        nextDayImage = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        menuLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mountainsLabel = new javax.swing.JLabel();
        gifLabel = new javax.swing.JLabel();
        colorPanelMain = new javax.swing.JPanel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        menu.setBackground(backgroundColor);
        menu.setComponentPopupMenu(menu.getComponentPopupMenu());

        jLabel2.setFont(new java.awt.Font("Arial Nova", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/details.png"))); // NOI18N
        jLabel2.setLabelFor(closeLabel);
        jLabel2.setText("Weather details");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Nova", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        jLabel3.setLabelFor(closeLabel);
        jLabel3.setText("Settings");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        getContentPane().add(menu);
        menu.setBounds(40, 10, 210, 70);

        minimizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseExited(evt);
            }
        });
        getContentPane().add(minimizeLabel);
        minimizeLabel.setBounds(250, 10, 20, 20);

        dayAfterTomorrowTempLabel.setFont(new java.awt.Font("Arial Nova", 0, 10)); // NOI18N
        dayAfterTomorrowTempLabel.setForeground(new java.awt.Color(102, 102, 102));
        dayAfterTomorrowTempLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dayAfterTomorrowTempLabel.setText("temp");
        getContentPane().add(dayAfterTomorrowTempLabel);
        dayAfterTomorrowTempLabel.setBounds(140, 450, 90, 20);

        nextDayTempLabel.setFont(new java.awt.Font("Arial Nova", 0, 10)); // NOI18N
        nextDayTempLabel.setForeground(new java.awt.Color(102, 102, 102));
        nextDayTempLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nextDayTempLabel.setText("temp");
        getContentPane().add(nextDayTempLabel);
        nextDayTempLabel.setBounds(140, 390, 90, 20);

        placeholderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        placeholderLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/placeholder.png"))); // NOI18N
        getContentPane().add(placeholderLabel);
        placeholderLabel.setBounds(40, 10, 20, 20);

        nextDayImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nextDayImage1);
        nextDayImage1.setBounds(240, 450, 40, 40);

        nextDayCondLabel1.setFont(new java.awt.Font("Arial Nova", 0, 10)); // NOI18N
        nextDayCondLabel1.setForeground(new java.awt.Color(102, 102, 102));
        nextDayCondLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nextDayCondLabel1.setText("cond");
        getContentPane().add(nextDayCondLabel1);
        nextDayCondLabel1.setBounds(110, 470, 120, 20);

        nextDayLabel1.setFont(new java.awt.Font("Arial Nova Cond", 0, 12)); // NOI18N
        nextDayLabel1.setForeground(new java.awt.Color(102, 102, 102));
        nextDayLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nextDayLabel1.setText("day");
        getContentPane().add(nextDayLabel1);
        nextDayLabel1.setBounds(20, 450, 80, 40);

        jSeparator1.setForeground(new java.awt.Color(234, 235, 237));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 440, 260, 10);

        nextDayCondLabel.setFont(new java.awt.Font("Arial Nova", 0, 10)); // NOI18N
        nextDayCondLabel.setForeground(new java.awt.Color(102, 102, 102));
        nextDayCondLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nextDayCondLabel.setText("cond");
        getContentPane().add(nextDayCondLabel);
        nextDayCondLabel.setBounds(110, 410, 120, 20);

        nextDayLabel.setFont(new java.awt.Font("Arial Nova Cond", 0, 12)); // NOI18N
        nextDayLabel.setForeground(new java.awt.Color(102, 102, 102));
        nextDayLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nextDayLabel.setText("day");
        getContentPane().add(nextDayLabel);
        nextDayLabel.setBounds(20, 390, 80, 40);

        nextDayImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nextDayImage);
        nextDayImage.setBounds(240, 390, 40, 40);

        temperatureLabel.setBackground(new java.awt.Color(255, 255, 255));
        temperatureLabel.setFont(new java.awt.Font("Arial Nova Cond", 0, 70)); // NOI18N
        temperatureLabel.setForeground(new java.awt.Color(255, 255, 255));
        temperatureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatureLabel.setText("temp");
        getContentPane().add(temperatureLabel);
        temperatureLabel.setBounds(20, 110, 260, 70);

        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu (1).png"))); // NOI18N
        menuLabel.setComponentPopupMenu(menu.getComponentPopupMenu());
        menuLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLabelMouseClicked(evt);
            }
        });
        getContentPane().add(menuLabel);
        menuLabel.setBounds(10, 10, 20, 20);

        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_button.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelMouseExited(evt);
            }
        });
        getContentPane().add(closeLabel);
        closeLabel.setBounds(270, 10, 20, 20);

        descriptionLabel.setFont(new java.awt.Font("Arial Nova", 0, 12)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("condition");
        getContentPane().add(descriptionLabel);
        descriptionLabel.setBounds(20, 180, 260, 20);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(imageLabel);
        imageLabel.setBounds(330, 70, 90, 160);

        locationLabel.setFont(new java.awt.Font("Arial Nova Cond", 0, 14)); // NOI18N
        locationLabel.setForeground(new java.awt.Color(51, 153, 255));
        locationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        locationLabel.setText("location");
        getContentPane().add(locationLabel);
        locationLabel.setBounds(60, 10, 200, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Webp.net-resizeimage (5).png"))); // NOI18N
        jLabel1.setText("X Close");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 510);

        mountainsLabel.setIcon(mountains);
        getContentPane().add(mountainsLabel);
        mountainsLabel.setBounds(0, 0, 300, 510);
        getContentPane().add(gifLabel);
        gifLabel.setBounds(0, 0, 300, 310);

        colorPanelMain.setBackground(backgroundColor);

        javax.swing.GroupLayout colorPanelMainLayout = new javax.swing.GroupLayout(colorPanelMain);
        colorPanelMain.setLayout(colorPanelMainLayout);
        colorPanelMainLayout.setHorizontalGroup(
            colorPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        colorPanelMainLayout.setVerticalGroup(
            colorPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(colorPanelMain);
        colorPanelMain.setBounds(0, 0, 300, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    int click = 1;
    private void menuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLabelMouseClicked
        click++;
        if( click % 2 == 0) {
            menu.setVisible(true);
        } else {
            menu.setVisible(false);
        }
    }//GEN-LAST:event_menuLabelMouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        cordsX = evt.getXOnScreen();
        cordsY = evt.getYOnScreen();
        
        this.setLocation( cordsX-mouseX, cordsY-mouseY);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        this.setExtendedState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void closeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseEntered
        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_button_hover.png")));
    }//GEN-LAST:event_closeLabelMouseEntered

    private void closeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseExited
        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_button.png")));
    }//GEN-LAST:event_closeLabelMouseExited

    private void minimizeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseEntered
        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize_hover.png")));
    }//GEN-LAST:event_minimizeLabelMouseEntered

    private void minimizeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseExited
        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png")));
    }//GEN-LAST:event_minimizeLabelMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        SettingsUI settings = new SettingsUI();
        settings.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        getCurrentWeatherDetails();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WeatherUI().setVisible(true);
        });
    }
    
    public void closeWindow(){
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel closeLabel;
    public static javax.swing.JPanel colorPanelMain;
    public static javax.swing.JLabel dayAfterTomorrowTempLabel;
    public static javax.swing.JLabel descriptionLabel;
    public static javax.swing.JLabel gifLabel;
    public static javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel locationLabel;
    private javax.swing.JPanel menu;
    private static javax.swing.JLabel menuLabel;
    private static javax.swing.JLabel minimizeLabel;
    public static javax.swing.JLabel mountainsLabel;
    public static javax.swing.JLabel nextDayCondLabel;
    public static javax.swing.JLabel nextDayCondLabel1;
    public static javax.swing.JLabel nextDayImage;
    public static javax.swing.JLabel nextDayImage1;
    public static javax.swing.JLabel nextDayLabel;
    public static javax.swing.JLabel nextDayLabel1;
    public static javax.swing.JLabel nextDayTempLabel;
    public static javax.swing.JLabel placeholderLabel;
    public static javax.swing.JLabel temperatureLabel;
    // End of variables declaration//GEN-END:variables
}
