package weather.app;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Kamil
 */
public class WeatherUI extends javax.swing.JFrame {

    /**
     * Creates new form WeatherUI
     */
    public WeatherUI() {
        initComponents();
        setLocation(810, 315);
        setSize(300, 518);
        setTitle("WeatherApp");
        //setResizable(false);
        setVisible(true);
        setDefaultCloseOperation(3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temperatureLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        descriptionLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        temperatureLabel.setBackground(new java.awt.Color(255, 255, 255));
        temperatureLabel.setFont(new java.awt.Font("Arial Nova Cond Light", 0, 44)); // NOI18N
        temperatureLabel.setForeground(new java.awt.Color(255, 255, 255));
        temperatureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatureLabel.setText("temp");
        getContentPane().add(temperatureLabel);
        temperatureLabel.setBounds(0, 150, 300, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu (1).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 20, 16);

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close(1).png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelMouseExited(evt);
            }
        });
        getContentPane().add(closeLabel);
        closeLabel.setBounds(270, 10, 16, 16);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sun.png"))); // NOI18N
        getContentPane().add(imageLabel);
        imageLabel.setBounds(0, 50, 300, 80);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(80, 2));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(110, 210, 80, 10);

        descriptionLabel.setFont(new java.awt.Font("Arial Nova", 0, 12)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("description");
        getContentPane().add(descriptionLabel);
        descriptionLabel.setBounds(0, 220, 300, 15);

        dateLabel.setBackground(new java.awt.Color(51, 51, 51));
        dateLabel.setFont(new java.awt.Font("Arial Nova Cond", 0, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(153, 153, 153));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("date");
        getContentPane().add(dateLabel);
        dateLabel.setBounds(20, 350, 130, 20);

        locationLabel.setFont(new java.awt.Font("Arial Nova Cond", 0, 14)); // NOI18N
        locationLabel.setForeground(new java.awt.Color(153, 153, 153));
        locationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        locationLabel.setText("location");
        getContentPane().add(locationLabel);
        locationLabel.setBounds(160, 350, 110, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jLabel1.setText("X Close");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 518);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void closeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseEntered
        Icon hoverIcon = new ImageIcon("src/images/close(2).png");
        closeLabel.setIcon(hoverIcon);
    }//GEN-LAST:event_closeLabelMouseEntered

    private void closeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseExited
        Icon icon = new ImageIcon("src/images/close(1).png");
        closeLabel.setIcon(icon);
    }//GEN-LAST:event_closeLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeLabel;
    public static javax.swing.JLabel dateLabel;
    public static javax.swing.JLabel descriptionLabel;
    public static javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel locationLabel;
    public static javax.swing.JLabel temperatureLabel;
    // End of variables declaration//GEN-END:variables
}
